#!/usr/bin/env bash
# One-time setup of Faffa Go on an Ubuntu 24.04 VPS, in Docker (phase 11, D-100).
#
#   sudo bash setup-server.sh
#
# The VPS already hosts other projects behind Nginx, so this script leaves them
# alone: Faffa Go runs in its own containers (compose project "faffago") on
# 127.0.0.1:4002 and 4001, and gets its own Nginx site. Firewall, time zone and
# other containers are not touched.
#
# Safe to run again: every step checks what is already there. It stops once,
# after printing the server's deploy key, if GitHub does not know it yet: add
# the key to the repository, then run it again. See docs/deployment.md.
set -euo pipefail

REPO_SSH="git@github.com:SeifeddineHamdi2001/faffago.git"
APP_DIR="/opt/faffago"
ENV_FILE="/etc/faffago/faffago.env"
DEPLOY_KEY="/root/.ssh/faffago_deploy"
DOCS_DIR="/var/lib/faffago/documents"
BACKUP_DIR="/var/backups/faffago"
APK_DIR="/var/www/faffago-apk"
NGINX_SITE="/etc/nginx/sites-available/faffago"
WEB_PORT=4002
API_PORT=4001
# The node user inside the app image, who writes the documents.
CONTAINER_UID=1000

step() { printf '\n\033[1;33m== %s\033[0m\n' "$*"; }
die() {
  echo "$*" >&2
  exit 1
}

[[ $EUID -eq 0 ]] || die "Run as root: sudo bash $0"
. /etc/os-release
[[ "${ID}" == "ubuntu" ]] || die "Written for Ubuntu 24.04; this is ${PRETTY_NAME}."

step "Packages (only what is missing)"
export DEBIAN_FRONTEND=noninteractive
apt-get update -q
apt-get install -y -q ca-certificates curl git rclone

step "Docker"
if ! docker compose version >/dev/null 2>&1; then
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  chmod a+r /etc/apt/keyrings/docker.asc
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu ${VERSION_CODENAME} stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -q
  apt-get install -y -q docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
fi
systemctl enable --now docker
docker compose version

step "Ports ${WEB_PORT} and ${API_PORT} are free"
if [[ ! -f "${ENV_FILE}" ]]; then
  for port in "${WEB_PORT}" "${API_PORT}"; do
    if ss -ltnH "sport = :${port}" | grep -q .; then
      die "Port ${port} is already used on this server: $(ss -ltnpH "sport = :${port}")"
    fi
  done
fi
echo "ok"

step "Swap (only if the server has none: building the image needs it on a small VPS)"
if ! swapon --show | grep -q .; then
  fallocate -l 2G /swapfile
  chmod 600 /swapfile
  mkswap /swapfile
  swapon /swapfile
  echo '/swapfile none swap sw 0 0' >> /etc/fstab
fi

step "Nginx and certbot"
command -v nginx >/dev/null || apt-get install -y -q nginx
command -v certbot >/dev/null || apt-get install -y -q certbot python3-certbot-nginx

step "Directories"
# Documents: on the host for the backups, outside anything Nginx serves, and
# writable only by the app container's user (D-32).
install -d -m 755 /var/lib/faffago
install -d -o "${CONTAINER_UID}" -g "${CONTAINER_UID}" -m 700 "${DOCS_DIR}"
install -d -m 700 "${BACKUP_DIR}"
install -d -o root -g www-data -m 750 "${APK_DIR}"
install -d -m 700 /etc/faffago

if [[ ! -f "${ENV_FILE}" ]]; then
  step "Production env file with fresh secrets: ${ENV_FILE}"
  rand() { openssl rand -base64 48 | tr -d '/+=\n' | cut -c1-40; }
  OWNER_PW="$(rand)"
  APP_PW="$(rand)"
  DOC_KEY="$(openssl rand -base64 32)"
  ADMIN_PW="$(rand | cut -c1-16)"
  umask 077
  cat > "${ENV_FILE}" <<ENV
# Faffa Go — production. Generated by deploy/setup-server.sh on $(date -I).
# Never commit, never send by chat or email. Keep a copy offline (docs/deployment.md).
NODE_ENV="production"

# The database runs in the "db" container; these passwords are set on it the
# first time its volume is created, so never change them afterwards.
FAFFAGO_OWNER_DB_PASSWORD="${OWNER_PW}"
FAFFAGO_APP_DB_PASSWORD="${APP_PW}"
DATABASE_URL="postgresql://faffago_app:${APP_PW}@db:5432/faffago?schema=public"
DATABASE_MIGRATION_URL="postgresql://faffago_owner:${OWNER_PW}@db:5432/faffago?schema=public"

# 4001 and 4002 on the host: the 3000s and 4000 are taken by other apps (D-100).
WEB_PORT=${WEB_PORT}
API_PORT=${API_PORT}
API_BASE_URL="http://api:${API_PORT}"

JWT_ACCESS_SECRET="$(openssl rand -base64 48 | tr -d '\n')"
JWT_REFRESH_SECRET="$(openssl rand -base64 48 | tr -d '\n')"

# The first admin: created by the seed on the first deploy. Afterwards the
# password lives hashed in the database; this line no longer matters.
FAFFAGO_ADMIN_USERNAME="admin"
FAFFAGO_ADMIN_PASSWORD="${ADMIN_PW}"
FAFFAGO_ADMIN_PHONE="20000000"

STORAGE_DRIVER="local"
# Inside the api container; on the host: ${DOCS_DIR}.
STORAGE_LOCAL_PATH="/data/documents"
# Losing this key loses every CIN / patente document. Copy it to two offline places.
STORAGE_ENCRYPTION_KEY_ID="k1"
STORAGE_ENCRYPTION_KEY="${DOC_KEY}"
STORAGE_ENCRYPTION_PREVIOUS_KEYS=""

# Printed in the QR code of every label: never change it once labels are printed (D-43).
NEXT_PUBLIC_SITE_URL="https://www.mirely.store"

# Off-server backups (deploy/backup.sh): an rclone remote and folder, e.g.
# "faffago-crypt:". Empty = backups stay on this server only, and the backup
# job fails on purpose so it is noticed.
BACKUP_RCLONE_REMOTE=""

SENTRY_DSN=""
ENV
  echo
  echo "Written. The first admin is 'admin' with password: ${ADMIN_PW}"
  echo "Copy ${ENV_FILE} to two offline places now (it holds the document key)."
else
  echo "${ENV_FILE} exists: kept as is."
fi
chown root:root "${ENV_FILE}"
chmod 600 "${ENV_FILE}"

step "The code"
if [[ ! -f "${DEPLOY_KEY}" ]]; then
  install -d -m 700 /root/.ssh
  ssh-keygen -q -t ed25519 -N '' -C "faffago-vps" -f "${DEPLOY_KEY}"
fi
ssh-keyscan -t ed25519 github.com >> /root/.ssh/known_hosts 2>/dev/null
sort -u -o /root/.ssh/known_hosts /root/.ssh/known_hosts
export GIT_SSH_COMMAND="ssh -i ${DEPLOY_KEY} -o IdentitiesOnly=yes"
if [[ ! -d "${APP_DIR}/.git" ]]; then
  if ! git clone -q "${REPO_SSH}" "${APP_DIR}"; then
    echo
    echo "GitHub refused the clone. Add this key to the repository:"
    echo "  GitHub > faffago > Settings > Deploy keys > Add deploy key (read-only)"
    echo
    cat "${DEPLOY_KEY}.pub"
    echo
    echo "Then run this script again."
    exit 2
  fi
fi
# deploy.sh pulls with the same key.
git -C "${APP_DIR}" config core.sshCommand "${GIT_SSH_COMMAND}"

step "Nightly backup timer"
install -m 644 "${APP_DIR}/deploy/systemd/faffago-backup.service" /etc/systemd/system/
install -m 644 "${APP_DIR}/deploy/systemd/faffago-backup.timer" /etc/systemd/system/
systemctl daemon-reload
systemctl enable --now faffago-backup.timer

step "Nginx site for Faffa Go"
# Installed once: certbot then adds the HTTPS parts to this file, and a rerun
# must not undo them. To take a newer deploy/nginx/faffago.conf, see the runbook.
if [[ ! -f "${NGINX_SITE}" ]]; then
  install -m 644 "${APP_DIR}/deploy/nginx/faffago.conf" "${NGINX_SITE}"
  ln -sfn "${NGINX_SITE}" /etc/nginx/sites-enabled/faffago
fi
nginx -t
systemctl reload nginx

step "Done"
cat <<NEXT
Next:
  1. DNS: A records for mirely.store, www.mirely.store and api.mirely.store -> this server.
  2. HTTPS: sudo certbot --nginx --redirect -d mirely.store -d www.mirely.store -d api.mirely.store
  3. First release:   sudo bash ${APP_DIR}/deploy/deploy.sh
  4. Check the roles: sudo bash ${APP_DIR}/deploy/check-db-roles.sh
  5. Off-server backups: docs/deployment.md, "Backups".
NEXT
